config/routes.rb
Rails.application.routes.draw do
  root to: 'statuses#index'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/timeline', to: 'users#timeline'
  get '/mentions', to: 'users#mentions'
  
  resources :users, only: [:index, :new, :create] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end
  
  resources :statuses, only: [:new, :create, :index, :show] do
    member do
      post 'retweet'
    end
  end
  
  resources :hashtags, only: [:show]
  
  get "/:username", to: 'users#show', as: 'user'
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
  
  def mark_viewed!
    self.update(viewed_at: Time.now)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: 'User', foreign_key: 'follower_id'
  belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :parent_status, class_name: 'Status', foreign_key: 'retweet_id'
  
  validates :creator, presence: true
  validates :body, presence: true, length: {minimum: 5}
  
  after_save :extract_mentions
  
  def extract_mentions
    mentions = self.body.scan(/@(\w*)/)
    if mentions.size > 0
      mentions.each do |mention|
        m = mention.first
        user = User.find_by username: m
        if user
          Mention.create(user_id: user.id, status_id: self.id)
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :statuses
  has_many :mentions
  
  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'leader_id'
  has_many :leader_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :follower_users, through: :follower_relationships, source: :follower
  has_many :following_users, through: :leader_relationships, source: :leader
  
  validates :username, presence: true
  validates :email, presence: true
  
  def num_unread_mentions
    mentions.where(viewed_at: nil).count
  end
  
  def unread_mentions
    mentions.where(viewed_at: nil)
  end
  
  def mark_unread_mentions!
    unread_mentions.each do |mention|
      mention.mark_viewed!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end
  
  def wrong_path
    flash[:error] = "There was an error."
    redirect_to root_path
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @statuses = Status.where("body LIKE ?", "%##{params[:id]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create    
    user = User.find_by username: params[:username]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, #{user.username}! You're logged in."
      redirect_to timeline_path
    else
      flash.now[:error] = "There is something wrong with your username or password."
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've logged out."
    redirect_to login_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  
  def index
    @statuses = Status.all
    
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def new
    @status = Status.new
  end
  
  def create
    @status = Status.new(status_params)
    @status.creator = current_user
    
    if @status.save
      flash[:notice] = "Status created!"
      redirect_to user_path(@status.creator.username)
    else
      render :new
    end
  end
  
  def show
    @status = Status.find(params[:id])
  end
  
  def retweet
    status = Status.find(params[:id])
    new_status = Status.new(body: status.body, creator: current_user, parent_status: status)
    if new_status.save
      flash[:notice] = "Retweeted!"
    else
      flash[:error] = "Couldn't retweet!"
    end
    redirect_to :back
  end
  
  private
  
  def status_params
    params.require(:status).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:follow, :unfollow, :timeline, :mentions]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:notice] = "You have registered!"
      session[:user_id] = @user.id
      redirect_to timeline_path
    else
      render :new
    end
  end
  
  def show
    @user = User.find_by username: params[:username]
    wrong_path unless @user
  end
  
  def follow
    user = User.find(params[:id])
    if user
      current_user.following_users << user
      flash[:notice] = "You are now following #{user.username}."
      redirect_to user_path(user.username)
    else
      wrong_path
    end
  end
  
  def unfollow
    user = User.find(params[:id])
    rel = Relationship.where(follower: current_user, leader: user).first
    if user && rel      
      rel.destroy    
      flash[:notice] = "You are no longer following #{user.username}."
      redirect_to user_path(user.username)
    else
      wrong_path
    end
  end
  
  def timeline
    @statuses = []
    current_user.following_users.each do |user|
      @statuses << user.statuses.all
    end
    @statuses.flatten!
  end
  
  def mentions
    current_user.mark_unread_mentions!
  end
  
  private
  
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auto_links(str)
    str = link_hashtag(str)
    str = link_mentions(str)
    str.html_safe
  end
  
  def link_hashtag(str)
    str.gsub(/#(\w+)/, "<a href='/hashtags/\\1'>#\\1</a>")
  end
  
  def link_mentions(str)
    str.gsub(/@(\w+)/, "<a href='/\\1'>@\\1</a>")
  end
  
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/views/hashtags/show.html.erb
<%= render 'shared/header', header: "Statuses for hashtag ##{params[:id]}" %>

<% @statuses.each do |status| %>
  <%= render 'statuses/status', status: status %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div>
  <% if flash.keys.any? %>
    <% flash.keys.each do |key| %>
      <div class = "container">
        <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> content-width" role="alert">
          <%= flash[key] %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  <ul class="nav navbar-nav">
    <li><%= nav_link 'Home', root_path %></li>
    <li><%= nav_link 'All Users', users_path %></li>
    <% if logged_in? %> 
      <li><%= nav_link 'Timeline', timeline_path %></li>
      <li><%= nav_link "Mentions <span class='badge'>#{current_user.num_unread_mentions}</span>".html_safe, mentions_path %></li>
      <li><%= nav_link 'New Status', new_status_path %></li>
    <% else %>
      <li><%= nav_link 'Register', new_user_path %></li>
      <li><%= nav_link 'Login', login_path %></li>
    <% end %>
  </ul>
  <% if logged_in? %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Hi, #{current_user.username}!", user_path(current_user.username) %></li>
      <li><%= nav_link 'Logout', logout_path %></li>
    </ul>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/top_nav' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="alert alert-danger content-width" role="alert">
      <h5>There were some errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="page-header">
  <h3><%= header %></h3>
</div>

app/views/shared/_no_content_info.html.erb
<div class="alert alert-info content-width" role="alert">
  <p>There are currently no statuses to display.</p>  
</div>

app/views/statuses/_status.html.erb
<div class="panel panel-default content-width">
  <div class="panel-body">
    <%= auto_links(status.body) %> <%= link_to '*', status_path(status.parent_status) if status.retweet_id %> 
    <% if status.retweet_id %>
      retweeted by
    <% else %>
      created by
    <% end %>
    <%= link_to status.creator.username, user_path(status.creator.username) %>
    at <%= status.created_at.strftime("%H:%M") %> on <%= status.created_at.strftime("%b %d, %Y") %>
    <% if logged_in? && status.creator != current_user%>
      [<%= link_to 'retweet', retweet_status_path(status), method: 'post' %>]
    <% end %>
  </div>
</div>
<br/>

app/views/statuses/index.html.erb
<%= render 'shared/header', header: "Recent statuses" %>

<% if !@statuses.empty? %>
  <% @statuses.each do |status| %>
    <%= render 'statuses/status', status: status %>
  <% end %>
<% else %>
    <%= render 'shared/no_content_info' %>
<% end %>

app/views/statuses/new.html.erb
<%= render 'shared/header', header: "Create a new status" %>
<%= render 'shared/errors', obj: @status %>

<%= form_for @status, html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-4">
      <%= f.text_area :body, class: "form-control", rows: "3" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create status", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/statuses/show.html.erb
<%= render 'status', status: @status %>

app/views/users/index.html.erb
<%= render 'shared/header', header: "All Users" %>

<div class="list-group content-width">
  <% @users.each do |user| %>
    <%= link_to user.username, user_path(user.username), class: "list-group-item" %>
  <% end %>
</div>

app/views/users/mentions.html.erb
<%= render 'shared/header', header: "Mentions" %>

<% if !current_user.mentions.empty? %>
  <% current_user.mentions.each do |mention| %>
    <%= render 'statuses/status', status: mention.status %>
  <% end %>
<% else %>
    <%= render 'shared/no_content_info' %>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/header', header: "Register" %>

<%= render 'shared/errors', obj: @user %>

<%= form_for @user, html: {class: "form-horizontal", role: "form"} do |f| %>
  <div class="form-group">
    <%= f.label :username, class: "col-sm-2 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :username, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-3">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-3">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Register", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h3><%= link_to "@#{@user.username}", user_path(@user.username) %></h3>
  <% if logged_in? && (@user != current_user) %>
    <% if !current_user.following_users.include?(@user) %>
      <h5><%= link_to "+ follow", follow_user_path(@user), method: 'post' %></h5>
    <% else %>
      <h5><%= link_to "- unfollow", unfollow_user_path(@user), method: 'post' %></h5>
    <% end %>
  <% end %>
</div>

<% @user.statuses.each do |status| %>
  <%= render 'statuses/status', status: status %></li>
<% end %>

app/views/users/timeline.html.erb
<%= render 'shared/header', header: "Timeline" %>

<% if !@statuses.empty? %>
  <% @statuses.each do |status| %>
    <%= render 'statuses/status', status: status %>
  <% end %>
<% else %>
    <%= render 'shared/no_content_info' %>
<% end %>